// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfghllfusjlodgxumbir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmZ2hsbGZ1c2psb2RneHVtYmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NzcyOTksImV4cCI6MjA4MzA1MzI5OX0.I4CwGHM8ebS3qmlzOoCE1ZhQQlMlrmkMrzNt_4voqpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
